version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: blio_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8076:80"
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "
        docker-php-ext-install pdo pdo_mysql &&
        apache2-foreground
      "
  db:
    image: mysql:8.0
    container_name: blio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blio
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3302:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blio_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  blio_data:
